/* Suggestions page (design brief 2026-09-27). Renders SUGG from suggestions-data.js; the server builds the
   list, this page only shows it and sends two actions: Download (SeerrDiscoverService.request) and No thanks. */
(function () {
  const D = window.SUGG, $ = id => document.getElementById(id);
  const esc = s => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const qp = new URLSearchParams(location.search);
  // round-1 questions; the lean of each is the default
  // owner decisions 2026-09-27 (Phase 274): Q1 admin · Q2 Download · Q3 20 + Show more · Q4 blacklist too · Q5 names
  const Q = { q1: 'admin', q2: 'Download', q3: 'more', q4: 'yes', q5: 'names' };
  // Q7: clusters are generated by AI on every build; the fixed six are the fallback (FR-274-5)
  let clusters = qp.get('clusters') || 'ai';
  let state = qp.get('state') || 'list', showMore = false, openPick = null, otherOn = null, dismissed = D.DISMISSED.slice();
  let list = D.LIST.map(x => Object.assign({}, x));
  const more = D.MORE.map(x => Object.assign({}, x));
  if (list.find(x => x.picker)) openPick = list.find(x => x.picker).id;

  const vname = id => (D.VIEWERS.find(v => v.id === id) || {}).name || id;
  const bucket = id => { const b = D.BUCKETS.find(x => x.id === id); return clusters === 'ai' ? Object.assign({}, b, { label: D.AI_NAMES[id] || b.label }) : b; };
  const grad = h => 'linear-gradient(160deg, hsl(' + h + ' 45% 34%), hsl(' + ((h + 30) % 360) + ' 55% 14%))';
  const mins = m => Math.floor(m / 60) + ' h ' + (m % 60) + ' min';
  function andList(a) { const t = a.map(x => '<i>' + esc(x) + '</i>'); return t.length < 2 ? t.join('') : t.slice(0, -1).join(', ') + ' and ' + t[t.length - 1]; }
  function because(it) {
    return 'because ' + it.because.map(([v, verb, titles]) => {
      const who = Q.q5 === 'names' ? esc(vname(v)) : 'someone in the household';
      return verb === 'watching' ? who + ' is watching ' + andList(titles.slice(0, 3)) : who + ' finished ' + andList(titles.slice(0, 3));
    }).join('; ');
  }
  const viewersOf = it => new Set(it.because.map(b => b[0])).size;
  function requester(it) {
    const main = vname(it.because[0][0]);
    return Q.q1 === 'admin' ? 'requested as Admin · note: for ' + (Q.q5 === 'names' ? esc(main) : 'the household') : 'requested as ' + esc(main);
  }

  function stateHTML(it) {
    if (it.state === 'requested') return '<div class="sg-state"><span class="badge warn">Requested</span><span class="tiny muted">waiting for approval in Seerr · ' + requester(it) + '</span></div>';
    if (it.state === 'approved') return '<div class="sg-state"><span class="badge info">Approved</span><span class="tiny muted">Radarr is looking for it · ' + requester(it) + '</span></div>';
    if (it.state === 'downloading') return '<div class="sg-state"><span class="badge info">Downloading · ' + it.pct + '%</span><span class="sg-bar"><i style="width:' + it.pct + '%"></i></span></div>';
    if (it.state === 'library') return '<div class="sg-state"><span class="badge ok">✓ In the library</span><span class="tiny muted">leaves this list on the next build</span></div>';
    return null;
  }
  function pickHTML(it) {
    const R = [
      ['Not interested', 'Out for good. What led here counts for a little less next time.'],
      ['Already seen it', 'Out, and counted as watched — it becomes something to suggest from.'],
      ['Too old', 'Out, and the next build leans a step newer.'],
      ['Other', 'Out. Your note is kept with it under Dismissed.'],
    ];
    return '<div class="sg-pick"><div class="ph">Why not?<span class="spacer" style="flex:1"></span><span class="btn sm ghost" data-cancel="' + it.id + '">Cancel</span></div>'
      + '<div class="sg-rs" style="grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr))">' + R.map(r => '<button class="sg-r' + (otherOn === it.id && r[0] === 'Other' ? ' on' : '') + '" data-reason="' + r[0] + '" data-id="' + it.id + '"><b>' + r[0] + '</b><span>' + r[1] + '</span></button>').join('') + '</div>'
      + (otherOn === it.id ? '<div class="sg-other"><textarea id="sg-note" placeholder="Optional — a word for whoever looks later"></textarea><span class="btn sm" data-other="' + it.id + '">Dismiss</span></div>' : '')
      + '<div class="sg-foot">' + (Q.q4 === 'no'
        ? 'Only this page forgets it — a viewer can still find and request it on their TV.'
        : 'Also added to Seerr’s blacklist — gone from every Request row on every TV, for everyone.') + '</div></div>';
  }
  function tileHTML(it) {
    const b = bucket(it.b), st = stateHTML(it), off = state === 'unreachable', n = viewersOf(it);
    const acts = st
      ? '<div class="sg-acts">' + (n > 1 ? '<span class="chip sg-multi">' + n + ' viewers</span>' : '') + '<span class="spacer"></span>' + st + '</div>'
      : '<div class="sg-acts">' + (n > 1 ? '<span class="chip sg-multi">' + n + ' viewers</span>' : '') + '<span class="spacer"></span>'
        + '<span class="btn sm ghost" data-no="' + it.id + '">No thanks</span>'
        + '<span class="btn sm primary" data-dl="' + it.id + '"' + (off ? ' aria-disabled="true"' : '') + '>' + Q.q2 + '</span>'
        + (off ? '<span class="sg-dis">Seerr can’t be reached right now — this waits until it’s back.</span>' : '')
        + (it.refused ? '<span class="sg-ref">' + esc(it.refused) + '</span>' : '') + '</div>';
    return '<div class="sg-tile' + (openPick === it.id && !st ? ' picking' : '') + '" data-tile="' + it.id + '">'
      + '<div class="sg-post" style="background:' + grad(b.hue + (it.year % 7) * 6) + '"><span>' + esc(it.title) + '</span></div>'
      + '<div class="sg-body">'
      +   '<div class="sg-t">' + esc(it.title) + '<span class="y">' + it.year + '</span></div>'
      +   '<div class="sg-meta"><span>★ ' + it.score.toFixed(1) + '</span><span>·</span><span>' + mins(it.mins) + '</span>' + (it.cert ? '<span class="sg-cert">' + esc(it.cert) + '</span>' : '') + (it.fresh ? '<span class="tiny muted">· new this year, few ratings yet</span>' : '') + '</div>'
      +   (it.syn ? '<div class="sg-syn">' + esc(it.syn) + '</div>' : '')
      +   '<div class="sg-why">' + because(it) + '</div>'
      +   (it.franchise ? '<div class="sg-fr">First of a series you don’t have — the match was <b>' + esc(it.franchise) + '</b>.</div>' : '')
      +   acts
      + '</div>'
      + (openPick === it.id && !st ? pickHTML(it) : '')
      + '</div>';
  }
  function bucketsHTML(items) {
    return D.BUCKETS.map(b0 => {
      const b = bucket(b0.id);
      const its = items.filter(x => x.b === b.id);
      if (!its.length) return '';   // a bucket with no candidates is absent, not empty
      return '<section class="sg-bucket"><div class="sg-bh"><h3>' + b.label + '</h3><span class="n">' + its.length + '</span>'
        + '<span class="ev">the household finished ' + b.finished + (clusters === 'ai' ? ' films like these' : ' ' + b.label.toLowerCase().replace(' & ', ' and ') + ' films') + '</span></div>'
        + '<div class="sg-grid">' + its.map(tileHTML).join('') + '</div></section>';
    }).join('');
  }
  function empty(h, p, btn) { return '<div class="card sg-empty"><h3>' + h + '</h3>' + (p ? '<p>' + p + '</p>' : '') + (btn || '') + '</div>'; }

  function render() {
    const shown = list.length;
    $('sg-built').textContent = state === 'first' ? 'Not built yet' : 'Built ' + D.built + ' · ' + shown + ' shown of 50';
    $('sg-dlink').textContent = 'Dismissed (' + dismissed.length + ')';
    $('sg-verb-sub').textContent = Q.q2;
    $('sg-who').innerHTML = '<span>Built from 112 finished films:</span>' + D.VIEWERS.map(v => v.finished
      ? '<span class="chip"><b>' + v.finished + '</b> ' + esc(v.name) + '</span>'
      : '<span class="chip none">' + esc(v.name) + ' · nothing finished yet</span>').join('');
    $('sg-grp').innerHTML = clusters === 'ai' ? '<span class="dot ok"></span> Grouped by AI this build · <a href="activity.html?view=jobs">see the answer</a>'
      : '<span class="dot warn"></span> Grouped by genre — ' + ({ off: 'AI was off', limit: 'this month’s AI limit was reached', bad: 'the AI answer couldn’t be used' }[clusters] || 'AI was off') + (clusters === 'bad' ? ' · <a href="activity.html?view=jobs">why</a>' : '');
    $('sg-conn').className = state === 'unreachable' ? 'badge warn' : 'badge ok';
    $('sg-conn').textContent = state === 'unreachable' ? '● Seerr unreachable' : '● Seerr connected';
    $('sg-banner').innerHTML = state === 'unreachable'
      ? '<div class="note warn" style="margin-top:14px;display:flex;gap:12px;align-items:center;"><span class="badge warn" style="flex:none;">Last built list</span><span class="tiny" style="flex:1;line-height:1.5;">Built ' + D.built + ' · Seerr couldn’t be reached since 09:12. The list is still true; <b>' + Q.q2 + '</b> waits until Seerr answers again.</span><span class="btn sm ghost" id="sg-retry">Try again</span></div>'
      : '';
    const m = $('sg-main');
    $('sg-who').style.display = state === 'nohistory' ? 'none' : '';
    if (state === 'nohistory') { m.innerHTML = empty('Suggestions appear once someone has finished a few films.', ''); return renderRest(); }
    if (state === 'first') { m.innerHTML = empty('Nothing built yet', 'The first list is built in the background from what the household has finished. It takes a few minutes; the page fills in when it is done.', '<span class="btn primary" data-build="1">Build now</span>'); return renderRest(); }
    if (state === 'nothing' || !list.length) { m.innerHTML = empty('Nothing new right now · ' + D.next, 'Everything suggested has been downloaded, requested or dismissed.', '<span class="btn" data-build="1">⟲ Rebuild now</span>'); return renderRest(); }
    let html = bucketsHTML(list);
    if (Q.q3 === 'more') {
      html += showMore ? '<div class="sg-fold">30 weaker matches</div>' + bucketsHTML(more)
        : '<div class="sg-more"><span class="btn" id="sg-showmore">Show 30 more</span><span class="tiny muted">weaker matches from the same build — the 20 above are the ones sized to the household</span></div>';
    } else html += '<div class="sg-fold">below the fold · 30 weaker matches</div>' + bucketsHTML(more);
    m.innerHTML = html;
    renderRest();
  }
  function renderRest() {
    const d = $('dismissed');
    d.style.display = location.hash === '#dismissed' ? '' : 'none';
    d.innerHTML = '<div class="row center"><h3 style="margin:0;font-size:1.05rem;">Dismissed</h3><span class="badge" style="margin-left:8px;">' + dismissed.length + '</span><span class="spacer"></span><a class="btn sm ghost" href="#">Close</a></div>'
      + '<p class="tiny muted" style="margin:6px 0 0;">Everything said no to, and why — and anything blacklisted in Seerr directly. None of it is suggested again; <b>Bring back</b> also takes it off Seerr’s blacklist.</p>'
      + (dismissed.length ? '<table class="sg-dtable"><thead><tr><th>Title</th><th>Reason</th><th>Who</th><th>When</th><th></th></tr></thead><tbody>'
        + dismissed.map((x, i) => '<tr><td><b>' + esc(x.title) + '</b> <span class="muted">' + x.year + '</span></td><td>' + esc(x.reason) + (x.note ? '<div class="tiny muted">“' + esc(x.note) + '”</div>' : '') + '</td><td>' + esc(x.who) + '</td><td class="tiny muted">' + esc(x.when) + '</td><td style="text-align:right"><span class="btn sm ghost" data-back="' + i + '">Bring back</span></td></tr>').join('')
        + '</tbody></table>' : '<p class="tiny muted">Nothing dismissed.</p>');
    renderQs();
  }
  function renderQs() {
    const QS = [
      ['Q1', 'Whose request', 'The admin’s own Seerr user; the viewer on the because line goes in the request’s note.'],
      ['Q2', 'The button', '<b>Download</b> — the chip says Requested until Seerr approves.'],
      ['Q3', 'List size', '20 shown of 50 built; <b>Show more</b> reveals the rest.'],
      ['Q4', 'Seerr’s blacklist', '<b>Yes.</b> No thanks also blacklists in Seerr, Undo and Bring back remove it, and the build skips anything on Seerr’s blacklist — whoever put it there.'],
      ['Q5', 'The because line', 'Names the viewers.'],
      ['Q6', 'Series as taste', '<b>Yes</b> — genre share only. Series weigh the clusters; they never produce candidates.'],
      ['Q7', 'The clusters', '<b>Generated by AI on every build</b> (a new AI job with its own limit). AI off, limit reached or an unusable answer ⇒ the fixed six, and the page says so.'],
    ];
    $('sg-qs').innerHTML = '<div class="row center"><h3 style="margin:0;font-size:1rem;">Decided · owner, 2026-09-27</h3><span class="badge ok" style="margin-left:8px;">Phase 274 · R320</span><span class="spacer"></span>'
      + '<span class="tiny muted">clusters preview:</span><span class="seg" id="sg-cl">' + [['ai', 'AI'], ['off', 'AI off'], ['limit', 'Limit reached'], ['bad', 'Bad answer']].map(x => '<span data-c="' + x[0] + '"' + (clusters === x[0] ? ' class="on"' : '') + '>' + x[1] + '</span>').join('') + '</span></div>'
      + QS.map(q => '<div class="sg-q"><span class="qn">' + q[0] + '</span><span class="qt">' + q[1] + '</span><span class="qd">' + q[2] + '</span></div>').join('')
      + dlQsHTML();
  }
  function dlQsHTML() {
    const L = '<span class="lean">lean</span>';
    const QD = [
      ['q1', 'Q1', 'Remember the last chosen quality for the next sheet', [['no', 'No — Seerr’s default every time'], ['yes', 'Yes — open on the last pick']], 'The default is Seerr’s own decision; the admin should see it each time.'],
      ['q2', 'Q2', 'Sheet or dialog', [['both', 'Sheet on narrow, dialog on wide'], ['dialog', 'Always a dialog'], ['sheet', 'Always a sheet']], 'The confirmation idiom of 260’s Empty queues panel.'],
      ['q3', 'Q3', 'Show the folder chooser', [['two', 'Only with two or more folders'], ['always', 'Always, under More'], ['never', 'Never']], 'The household has one folder per server today, so round 1 draws nothing unless Seerr reports two.'],
      ['q4', 'Q4', 'Free space beside a folder', [['yes', 'Yes, as Seerr reports it'], ['no', 'No']], 'The one fact that changes the choice.'],
      ['q5', 'Q5', 'Should No thanks get a confirm too', [['no', 'No — it has Undo and Bring back'], ['yes', 'Yes']], 'A confirm on both would make the page slow to use. Recorded; not drawn.'],
    ];
    return ''; // owner 2026-09-28: decided — panel removed
    return '<div class="row center" style="margin-top:22px;padding-top:14px;border-top:1px solid var(--line)"><h3 style="margin:0;font-size:1rem;">Download asks first · decided</h3><span class="badge ok" style="margin-left:8px;">owner 2026-09-28 · amends FR-274-10</span><span class="spacer"></span><span class="tiny muted">picks switch the sheet live</span></div>'
      + QD.map(q => '<div class="sg-q"><span class="qn">' + q[1] + '</span><span class="qt">' + q[2] + '</span><span class="seg" data-dq="' + q[0] + '">' + q[3].map((o, i) => '<span data-v="' + o[0] + '"' + (DQ[q[0]] === o[0] ? ' class="on"' : '') + '>' + o[1] + (o[0] === DQPICK[q[0]] ? '<span class="lean">decided</span>' : '') + '</span>').join('') + '</span><span class="qd">' + q[4] + '</span></div>').join('');
  }

  function toast(m) { const t = document.createElement('div'); t.className = 'toast'; t.textContent = m; document.body.appendChild(t); setTimeout(() => t.remove(), 1900); }
  let undoT = null;
  function undoToast(item, entry) {
    document.querySelectorAll('.sg-undo').forEach(x => x.remove()); clearTimeout(undoT);
    const u = document.createElement('div'); u.className = 'sg-undo';
    u.innerHTML = '<span>Dismissed · ' + esc(item.title) + '</span><span class="btn sm" id="sg-undo-btn">Undo</span>';
    document.body.appendChild(u);
    u.querySelector('#sg-undo-btn').onclick = () => { dismissed = dismissed.filter(x => x !== entry); list.splice(item._idx, 0, item); u.remove(); render(); };
    undoT = setTimeout(() => u.remove(), 6000);
  }
  function dismiss(id, reason, note) {
    const pool = list.find(x => x.id === id) ? list : more;
    const idx = pool.findIndex(x => x.id === id); const it = pool[idx];
    const el = document.querySelector('[data-tile="' + id + '"]');
    const entry = { title: it.title, year: it.year, reason, note, who: 'Admin', when: 'just now' };
    dismissed.unshift(entry); openPick = null; otherOn = null;
    const go = () => { pool.splice(idx, 1); it._idx = idx; render(); if (pool === list) undoToast(it, entry); };
    if (el) { el.classList.add('leaving'); setTimeout(go, 220); } else go();
  }
  /* §8 (2026-09-28) — Download asks first. The sheet's options are Seerr's own (GET /service/radarr and
     /service/radarr/{id}), fetched when the sheet opens and cached for the page's life; never a setting here. */
  const SRV_HD = { id: 0, name: 'Radarr', is4k: false, isDefault: true, active: 4, profiles: [[1, 'Any'], [4, 'HD-1080p'], [6, 'HD - 720p/1080p']], folders: [['/data/films', '2.1 TB'], ['/data/films-family', '740 GB']], activeFolder: 0 };
  const SRV = {
    one: [Object.assign({}, SRV_HD, { folders: [['/data/films', '2.1 TB']] })],
    two: [SRV_HD, { id: 1, name: 'Radarr 4K', is4k: true, isDefault: false, active: 5, profiles: [[5, 'Ultra-HD'], [1, 'Any']], folders: [['/data/films-4k', '3.4 TB']], activeFolder: 0 }],
    single: [Object.assign({}, SRV_HD, { profiles: [[4, 'HD-1080p']], folders: [['/data/films', '2.1 TB']] })],
  };
  // owner 2026-09-28: Q2 always a dialog, Q4 no free space; Q1/Q3/Q5 the leans
  const DQ = { q1: 'no', q2: 'dialog', q3: 'two', q4: 'no', q5: 'no' };
  const DQPICK = { q1: 'no', q2: 'dialog', q3: 'two', q4: 'no', q5: 'no' };
  let dlPrev = 'live', dl = null, cached = false, lastPick = null;
  const servers = () => SRV[dlPrev === 'two' ? 'two' : dlPrev === 'single' ? 'single' : 'one'];
  function openDl(id) {
    const srv = servers()[0];
    let prof = srv.active;
    if (DQ.q1 === 'yes' && lastPick && srv.profiles.some(p => p[0] === lastPick)) prof = lastPick;
    dl = { id, srv: 0, prof, folder: srv.activeFolder, more: false, phase: (dlPrev === 'loading' || (!cached && dlPrev === 'live')) ? 'loading' : 'ready' };
    renderDl();
    if (dl.phase === 'loading' && dlPrev !== 'loading') setTimeout(() => { if (dl && dl.id === id) { cached = true; dl.phase = 'ready'; renderDl(); } }, 900);
  }
  function closeDl() { dl = null; const r = $('sg-dlroot'); if (r) r.remove(); }
  function renderDl() {
    let root = $('sg-dlroot');
    if (!dl) { if (root) root.remove(); return; }
    if (!root) { root = document.createElement('div'); root.id = 'sg-dlroot'; document.body.appendChild(root); }
    const it = list.concat(more).find(x => x.id === dl.id), b = bucket(it.b), S = servers(), srv = S[dl.srv];
    const prof = srv.profiles.find(p => p[0] === dl.prof) || srv.profiles[0];
    const loading = dl.phase === 'loading', down = dlPrev === 'unreachable', fixed = dlPrev === 'nochoose';
    const def = p => p[0] === srv.active;
    let body = '';
    if (loading) body = '<div class="sg-dls"><div class="lb">Quality</div><div class="sg-skel"><i></i><i></i><i></i></div><div class="tiny muted">Asking Seerr which qualities Radarr has…</div></div>';
    else if (down) body = '<div class="sg-dldown"><span class="dot warn"></span><span>Seerr can’t be reached right now — this waits until it’s back.</span><span class="btn sm ghost" data-dlretry="1">Try again</span></div>';
    else {
      if (S.length > 1) body += '<div class="sg-dls"><div class="lb">Server <span>Seerr has ' + S.length + ' Radarr servers</span></div><div class="sg-srvs">'
        + S.map((s, i) => '<button class="sg-srv' + (i === dl.srv ? ' on' : '') + '" data-dlsrv="' + i + '"><b>' + esc(s.name) + '</b>' + (s.is4k ? '<span class="sg-4k">4K</span>' : '') + '<span class="tiny muted">' + s.profiles.length + ' qualit' + (s.profiles.length === 1 ? 'y' : 'ies') + (s.isDefault ? ' · Seerr’s default server' : '') + '</span></button>').join('') + '</div></div>';
      const oneProf = srv.profiles.length === 1;
      body += '<div class="sg-dls"><div class="lb">Quality <span>as Radarr names them' + (S.length > 1 ? '' : ' · to <b>' + esc(srv.name) + '</b>') + '</span></div>';
      if (fixed || oneProf) body += '<div class="sg-fact"><b>' + esc(prof[1]) + '</b><span class="sg-def">Seerr’s default</span></div>'
        + '<div class="tiny muted" style="margin-top:6px;line-height:1.45">' + (fixed ? 'The admin’s Seerr user may not choose a quality, so Seerr uses its default. Seerr’s <i>Advanced requests</i> permission lets it choose.' : 'This is the only quality Radarr has on ' + esc(srv.name) + '.') + '</div>';
      else body += '<div class="sg-opts" role="radiogroup">' + srv.profiles.map(p => '<button class="sg-opt' + (p[0] === prof[0] ? ' on' : '') + '" role="radio" aria-checked="' + (p[0] === prof[0]) + '" data-dlprof="' + p[0] + '"><i></i><b>' + esc(p[1]) + '</b>' + (def(p) ? '<span class="sg-def">Seerr’s default</span>' : '') + (DQ.q1 === 'yes' && lastPick === p[0] && !def(p) ? '<span class="sg-def last">your last choice</span>' : '') + '</button>').join('') + '</div>';
      body += '</div>';
      const showFolder = DQ.q3 === 'always' || (DQ.q3 === 'two' && srv.folders.length > 1);
      if (showFolder) {
        const f = srv.folders[dl.folder] || srv.folders[0];
        body += '<div class="sg-dls"><button class="sg-morebtn" data-dlmore="1">' + (dl.more ? '▾' : '▸') + ' More <span class="tiny muted">folder · ' + esc(f[0]) + (DQ.q4 === 'yes' ? ' · ' + f[1] + ' free' : '') + '</span></button>'
          + (dl.more ? '<div class="sg-opts" style="margin-top:8px">' + srv.folders.map((x, i) => '<button class="sg-opt' + (i === dl.folder ? ' on' : '') + '" data-dlfold="' + i + '"><i></i><b class="mono">' + esc(x[0]) + '</b>' + (DQ.q4 === 'yes' ? '<span class="tiny muted">' + x[1] + ' free</span>' : '') + (i === srv.activeFolder ? '<span class="sg-def">Seerr’s default</span>' : '') + '</button>').join('') + '</div>' : '') + '</div>';
      }
    }
    const who = vname(it.because[0][0]);
    body += '<div class="sg-dlnote"><span class="lb">Kept with the request</span><span>Suggested for ' + esc(Q.q5 === 'names' ? who : 'the household') + '</span><span class="tiny muted">Seerr has no note field, so this stays on this page (under the tile and in Dismissed / Requested).</span></div>';
    const primary = loading ? 'Asking Seerr…' : down ? 'Download' : 'Download in ' + prof[1] + (srv.is4k ? ' · 4K' : '');
    const mode = DQ.q2 === 'dialog' ? ' as-dialog' : DQ.q2 === 'sheet' ? ' as-sheet' : '';
    root.innerHTML = '<div class="sg-dlb' + mode + '" data-dlback="1"><div class="sg-dl" role="dialog" aria-modal="true" aria-label="Download ' + esc(it.title) + '">'
      + '<div class="sg-grab"></div>'
      + '<div class="sg-dlh"><div class="sg-post" style="width:64px;background:' + grad(b.hue + (it.year % 7) * 6) + '"><span>' + esc(it.title) + '</span></div>'
      + '<div style="min-width:0"><div class="sg-t">' + esc(it.title) + '<span class="y">' + it.year + '</span>' + (it.cert ? '<span class="sg-cert" style="margin-left:8px">' + esc(it.cert) + '</span>' : '') + '</div><div class="sg-why" style="margin-top:5px">' + because(it) + '</div></div></div>'
      + body
      + '<div class="sg-dlf">' + (down ? '<span class="tiny muted" style="flex:1">Nothing is sent while Seerr is away.</span>' : '<span style="flex:1"></span>') + '<span class="btn ghost" data-dlcancel="1">Cancel</span><span class="btn primary" data-dlgo="1"' + (loading || down ? ' aria-disabled="true"' : '') + '>' + esc(primary) + '</span></div>'
      + '</div></div>';
    const go = root.querySelector('[data-dlgo]'); if (go && !loading && !down) go.focus();
  }
  function confirmDl() {
    const S = servers(), srv = S[dl.srv], id = dl.id;
    lastPick = dl.prof;
    const it = list.concat(more).find(x => x.id === id);
    closeDl();
    if (dlPrev === 'refused') { it.refused = 'Seerr refused it — someone requested this film since the list was built.'; render(); return; }
    it.refused = null;
    download(id, srv.profiles.find(p => p[0] === lastPick)[1] + (srv.is4k ? ' · 4K' : ''));
  }
  function download(id, prof) {
    const it = list.concat(more).find(x => x.id === id);
    it.state = 'requested'; render();
    if (prof) toast('Requested in ' + prof + ' · ' + it.title);
    // mock: Seerr's auto-approve answers, then Radarr starts — the chip follows what comes back
    setTimeout(() => { it.state = 'approved'; render(); }, 1600);
    setTimeout(() => { it.state = 'downloading'; it.pct = 3; render(); }, 3600);
  }

  document.addEventListener('click', e => {
    const d = e.target.closest('[data-dlgo],[data-dlcancel],[data-dlsrv],[data-dlprof],[data-dlfold],[data-dlmore],[data-dlretry],[data-dlback]');
    if (d && dl) {
      if (d.dataset.dlback && e.target !== d) return;
      if (d.dataset.dlgo) return d.getAttribute('aria-disabled') ? null : confirmDl();
      if (d.dataset.dlcancel || d.dataset.dlback) return closeDl();
      if (d.dataset.dlsrv != null) { dl.srv = +d.dataset.dlsrv; const s = servers()[dl.srv]; dl.prof = s.active; dl.folder = s.activeFolder; return renderDl(); }
      if (d.dataset.dlprof) { dl.prof = +d.dataset.dlprof; return renderDl(); }
      if (d.dataset.dlfold != null) { dl.folder = +d.dataset.dlfold; return renderDl(); }
      if (d.dataset.dlmore) { dl.more = !dl.more; return renderDl(); }
      if (d.dataset.dlretry) { toast('Still no answer from Seerr'); return; }
    }
    const t = e.target.closest('[data-dl],[data-no],[data-cancel],[data-reason],[data-other],[data-back],[data-build],#sg-showmore,#sg-rebuild,#sg-retry,.seg > span');
    if (!t) return;
    if (t.dataset.dl) return t.getAttribute('aria-disabled') ? null : openDl(t.dataset.dl);
    if (t.dataset.no) { openPick = t.dataset.no; otherOn = null; return render(); }
    if (t.dataset.cancel) { openPick = null; otherOn = null; return render(); }
    if (t.dataset.reason) { if (t.dataset.reason === 'Other') { otherOn = t.dataset.id; render(); const n = $('sg-note'); if (n) n.focus(); return; } return dismiss(t.dataset.id, t.dataset.reason); }
    if (t.dataset.other) { const n = $('sg-note'); return dismiss(t.dataset.other, 'Other', n && n.value.trim()); }
    if (t.dataset.back != null) { const x = dismissed.splice(+t.dataset.back, 1)[0]; toast(x.title + ' · removed from Seerr’s blacklist · may return on the next build'); return render(); }
    if (t.dataset.build || t.id === 'sg-rebuild') { toast('Queued · the list rebuilds in the background'); if (state === 'first' || state === 'nothing') setTimeout(() => { state = 'list'; syncSeg(); render(); }, 1400); return; }
    if (t.id === 'sg-showmore') { showMore = true; return render(); }
    if (t.id === 'sg-retry') { toast('Still no answer from Seerr'); return; }
    const sg = t.closest('.seg');
    if (sg && sg.id === 'sg-state') { state = t.dataset.s; syncSeg(); return render(); }
    if (sg && sg.id === 'sg-cl') { clusters = t.dataset.c; return render(); }
    if (sg && sg.id === 'sg-dlprev') {
      dlPrev = t.dataset.p; syncSeg();
      if (state === 'unreachable') { state = 'list'; syncSeg(); render(); }
      const first = list.find(x => !x.state); if (first) openDl(first.id); return;
    }
    if (sg && sg.dataset.dq) { DQ[sg.dataset.dq] = t.dataset.v; renderQs(); if (dl) renderDl(); return; }
  });
  document.addEventListener('keydown', e => { if (e.key === 'Escape' && dl) closeDl(); });
  function syncSeg() {
    document.querySelectorAll('#sg-state span').forEach(s => s.classList.toggle('on', s.dataset.s === state));
    document.querySelectorAll('#sg-dlprev span').forEach(s => s.classList.toggle('on', s.dataset.p === dlPrev));
  }
  window.addEventListener('hashchange', renderRest);
  syncSeg(); render();
})();
