package dev.jellystructure.shared.wire

import kotlinx.cinterop.ByteVar
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.allocArray
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.pointed
import kotlinx.cinterop.toKString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import platform.posix.closedir
import platform.posix.fclose
import platform.posix.fgets
import platform.posix.fopen
import platform.posix.fputs
import platform.posix.getenv
import platform.posix.opendir
import platform.posix.readdir
import kotlin.test.Test

/**
 * R319 (FR-R319-2) — merges the per-release contracts in `$WIRE_BASELINE_DIR` (one `<tag>.json` each, from
 * [WireContractRecordTest]) into `$WIRE_BASELINE_KT`. Does nothing without them; run by
 * `scripts/record-wire-baseline.sh`.
 */
@OptIn(ExperimentalForeignApi::class)
class WireBaselineMergeTest {
    @Test
    fun merge() {
        val dir = getenv("WIRE_BASELINE_DIR")?.toKString() ?: return
        val outKt = getenv("WIRE_BASELINE_KT")?.toKString() ?: return
        val floor = getenv("WIRE_FLOOR")?.toKString() ?: error("WIRE_FLOOR not set")
        val files = listDir(dir).filter { it.endsWith(".json") }.sortedWith(compareBy { tagOrder(it.removeSuffix(".json")) })
        require(files.isNotEmpty()) { "no contracts in $dir" }
        val merged = WireContract.merge(files.map { Json.parseToJsonElement(readText("$dir/$it")).jsonObject })
        val tags = files.map { it.removeSuffix(".json") }
        val json = merged.toString()
        val chunks = json.chunked(20_000).joinToString(",\n") { "    \"\"\"$it\"\"\"" }
        writeText(outKt, buildString {
            appendLine("// Generated by scripts/record-wire-baseline.sh (R319) — do not edit; regenerate it.")
            appendLine("package dev.jellystructure.shared.wire")
            appendLine()
            appendLine("/** The oldest release whose apps must keep working (FR-R319-4): moving it drops support for older apps. */")
            appendLine("internal const val WIRE_FLOOR = \"$floor\"")
            appendLine()
            appendLine("/** The releases merged into [WIRE_BASELINE]. */")
            appendLine("internal val WIRE_BASELINE_TAGS = listOf(${tags.joinToString(", ") { "\"$it\"" }})")
            appendLine()
            appendLine("/** The strictest wire contract those releases imply (see [WireContract.merge]). */")
            appendLine("internal val WIRE_BASELINE: String = listOf(")
            appendLine(chunks)
            appendLine(").joinToString(\"\")")
        })
    }

    private fun tagOrder(t: String): Int = t.removePrefix("v").split('.').let { (it[0].toIntOrNull() ?: 0) * 1000 + (it.getOrNull(1)?.toIntOrNull() ?: 0) }

    private fun listDir(dir: String): List<String> {
        val d = opendir(dir) ?: error("cannot open $dir")
        val names = ArrayList<String>()
        try { while (true) { val e = readdir(d) ?: break; names += e.pointed.d_name.toKString() } } finally { closedir(d) }
        return names
    }

    private fun readText(path: String): String = memScoped {
        val f = fopen(path, "r") ?: error("cannot read $path")
        val buf = allocArray<ByteVar>(65_536)
        val sb = StringBuilder()
        try { while (fgets(buf, 65_536, f) != null) sb.append(buf.toKString()) } finally { fclose(f) }
        sb.toString()
    }

    private fun writeText(path: String, text: String) {
        val f = fopen(path, "w") ?: error("cannot write $path")
        try { fputs(text, f) } finally { fclose(f) }
    }
}
