@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "dev.jellystructure.shared"
    compileSdk = 36
    defaultConfig { minSdk = 21 }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
        }
    }

    linuxX64()

    wasmJs {
        browser()
    }

    // R189, superseded by R264 — Kotlin/JS IR (distinct from wasmJs above): compiles to plain,
    // old-engine-compatible JS (no WasmGC requirement), so ravilo-screen can target 2016-2018 Samsung
    // Tizen TVs, whose bundled WebKit/Chromium predates even non-GC WebAssembly (Chrome 57, 2017).
    js(IR) {
        browser()
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.websockets)
            }
        }
    }
}

// R252 (FR-R252-1) — dev.jellystructure.shared.BuildInfo, the one version every client reports, from the
// root project's resolved buildVersion (see the root build script for the precedence). Same wiring as
// the root's own generator: srcDir plus an explicit dependency on every Kotlin compile task.
val buildVersion = rootProject.extra["buildVersion"] as String
val buildInfoDir = layout.buildDirectory.dir("generated/buildinfo/commonMain/kotlin")
val generateBuildInfo by tasks.registering {
    val version = buildVersion
    val outDir = buildInfoDir
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("dev/jellystructure/shared/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "// Generated by the generateBuildInfo task (R252) — do not edit, do not commit.\n" +
                "package dev.jellystructure.shared\n\n" +
                "object BuildInfo {\n" +
                "    /** What this client was built as: a release (\"1.18\"), a `git describe` string for a sideload, or \"dev\". */\n" +
                "    const val version: String = \"" + version.replace("\\", "\\\\").replace("\"", "\\\"") + "\"\n" +
                "}\n",
        )
    }
}
kotlin.sourceSets.getByName("commonMain").kotlin.srcDir(generateBuildInfo.map { buildInfoDir.get() })
tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }.configureEach { dependsOn(generateBuildInfo) }
