#!/usr/bin/env python3
"""R319 — print WireRoots.kt for a source tree: the payloads an app decodes (responses) and sends
(requests), limited to the types that tree actually has. Usage: wire_roots.py <tree-root>"""
import glob, re, sys

RESPONSES = ['AccountPasswordResult', 'AccountPhotoResult', 'AcquisitionChangedEnvelope', 'AcquisitionRecord',
    'BrowseFacets', 'CardPlayState', 'CastHandoffResponse', 'Channel', 'DeviceStatusEnvelope', 'DiscoverDetail',
    'DiscoverEntry', 'DiscoverResponse', 'HomeFeed', 'LiveTvChannel', 'LiveTvGuideProgram', 'LiveTvStreamTicket',
    'MediaCard', 'MovieDetail', 'NavigateEnvelope', 'PairResult', 'PlayItemEnvelope', 'PlayerCommandEnvelope',
    'PlaystateChangedEnvelope', 'PlaystateCommandEnvelope', 'RaviloConfig', 'RemoteDevice', 'RemotePairResponse',
    'ScreenCodeResponse', 'SearchResults', 'SeededBrowseResponse', 'SeerrSearchResults', 'SeriesDetail',
    'ServerMessageEnvelope', 'StreamTicket', 'TvEvent', 'UpcomingDetail', 'UpcomingFeed']
REQUESTS = ['CastRedeemRequest', 'FavoriteRequest', 'LiveTvStopRequest', 'LiveTvTuneRequest', 'MarkRequest',
    'PlaybackProgressRequest', 'PlaybackQoeReport', 'PlaybackRestreamRequest', 'PlaybackStartRequest',
    'PlaybackStopRequest', 'PlayedRequest', 'RemoteCommandRequest', 'RemotePairRequest', 'RemotePlayRequest',
    'ScreenClaimRequest', 'ScreenCodeRequest', 'ScreenStatus', 'SeededBrowseRequest', 'TvLoginRequest',
    'ViewerSettingsRequest']

src = ''.join(open(f).read() for f in glob.glob(sys.argv[1] + '/shared/src/commonMain/kotlin/**/*.kt', recursive=True))
def has(n):   # a @Serializable class in package dev.jellystructure.shared.tv
    return re.search(r'@Serializable[^\n]*\n(?:\s*@[^\n]*\n)*\s*(?:data |sealed |open )?class ' + n + r'\b', src) is not None

print('// Generated by scripts/wire_roots.py (R319) — do not edit; edit the lists in the script.')
print('package dev.jellystructure.shared.wire\n')
print('import dev.jellystructure.shared.tv.*\n')
print('val WIRE_ROOTS: List<WireRoot> = listOf(')
for n in RESPONSES:
    if has(n): print(f'    WireRoot("{n}", WireDir.RESPONSE, {n}.serializer()),')
for n in REQUESTS:
    if has(n): print(f'    WireRoot("{n}", WireDir.REQUEST, {n}.serializer()),')
print(')')
