/* Desktop · D1 — round 2: size classes, compact = the phone, Medium, the queue by size, the System theme. Builders: desktop-kit.js. */
(function () {
  const { ic, bg, NOW, macTb, gnHb, gnSide, filmsHome, listen, albumPage, nowPlaying, mac, gn } = window.DK;
  const out = [];
  const frame = (x, y, id, h, note, html, w) => out.push(`<div class="frm" data-screen-label="${id}" style="left:${x}px;top:${y}px;${w ? 'width:' + w + 'px' : ''}"><div class="cap"><b>${id}</b><h3>${h}</h3></div>${html}${note ? `<p class="note">${note}</p>` : ''}</div>`);
  const head = (y, h, p) => out.push(`<div class="rowh" style="left:0;top:${y}px"><h2>${h}</h2>${p ? `<p>${p}</p>` : ''}</div>`);
  const L = '<div class="lights"><i></i><i></i><i></i></div>';
  const cwin = (p, skin, q, tag) => `<div class="win cwin ${p}" data-skin="${skin}"><div class="cstrip${p === 'gn' ? ' gnh' : ''}">${p === 'mac' ? L : ''}<span class="tag">${tag}</span>${p === 'gn' ? `<span class="gx">${ic('x')}</span>` : ''}</div><iframe src="Ravilo Mobile.html?frame=window&amp;${q}" title="${tag}"></iframe></div>`;

  let y = 0;
  head(y, 'Ravilo on the desktop — D1, round 2', 'The owner picked D1 (2026-09-30). This round draws what the picks leave open: <em style="color:#fff;font-style:normal">one layout family across four window sizes</em>, the compact window as the phone itself (shared Compose code), the rail for the in-between size, the queue at each size, and two new themes, <em style="color:#fff;font-style:normal">Graphite</em> and <em style="color:#fff;font-style:normal">Daylight</em>, with a light pick and a dark pick that follow the system.');
  y += 150;
  out.push(`<div class="frm" style="left:0;top:${y}px"><div class="fams">
    <div class="fam"><h5>TV</h5><b>Samsung · Android TV · Chromecast receiver · the web app (for now)</b>A remote, a sofa, 1920 × 1080. Focus-driven. The web app renders this family until it earns its own.</div>
    <div class="fam"><h5>Desktop</h5><b>macOS · GNOME (Flatpak) · more later</b>A pointer and a keyboard. Sidebar, rail or the phone’s layout, depending on the window width. Shapes and behaviour come from the platform; content and player are Ravilo’s.</div>
    <div class="fam"><h5>Mobile</h5><b>Android · the iPhone web app · every desktop window under 600 dp</b>Touch. The bottom bar and the Profile mode card. A narrow desktop window renders these same screens unchanged; only the window strip is the desktop’s.</div></div></div>`);
  y += 210;
  const R = [
    ['Navigation', 'The phone’s <em>bottom bar</em>', 'A <em>rail</em>: icon + label, 76–84 px', 'The <em>sidebar</em> (D1)', 'The sidebar'],
    ['Films ⇄ music', 'Profile ▸ the phone’s <em>mode card</em>', 'A two-icon toggle at the top of the rail', 'The segmented control heading the sidebar', 'Same'],
    ['Player', 'The phone’s mini bar above the bottom bar', 'Capsule (mac) / bar (GNOME), without volume slider and lyrics button', 'Full capsule / bar', 'Full'],
    ['Queue', 'A page (the phone’s Queue tab)', 'A panel <em>over</em> the content, from the right; Esc or a click outside closes it', 'Over the content', 'A side panel that <em>pushes</em> the content'],
    ['Playing', 'The phone’s Playing tab', 'A page: cover above lyrics', 'Cover (280) beside lyrics', 'Cover (380) beside lyrics'],
    ['Window chrome', 'A 32 px strip: traffic lights (mac) / close (GNOME); the rest is the phone', 'Traffic lights in the rail’s glass (mac) / the menu above the rail (GNOME)', 'Inset glass sidebar (mac) / split view (GNOME)', 'Same'],
    ['Compose', '<code class="kb">NavigationSuiteScaffold</code> → NavigationBar; the phone’s screens', 'NavigationRail; single pane', 'Our sidebar; list + overlay pane', 'List + supporting pane'],
  ];
  out.push(`<div class="frm" style="left:0;top:${y}px"><div class="ruler"><div class="h k" style="background:#2b2c33"></div><div class="h">Compact<small>&lt; 600 dp · the phone</small></div><div class="h">Medium<small>600–839 dp · the in-between</small></div><div class="h">Expanded<small>840–1199 dp</small></div><div class="h">Large<small>≥ 1200 dp</small></div>${R.map(r => `<div class="k">${r[0]}</div>` + r.slice(1).map(c => `<div>${c}</div>`).join('')).join('')}</div>
    <p class="note" style="max-width:2400px">The breakpoints are Compose’s own window size classes, so the phone, the rail and the sidebar come from one adaptive scaffold rather than three apps. Each size collapses into the one to its left; nothing new appears at a size. ⌘1 / ⌘2 (Ctrl+1 / Ctrl+2) switch mode at every size, including the phone layout.</p></div>`);
  y += 640;

  head(y, 'Compact · under 600 dp · the phone, in a window', 'These are <em style="color:#fff;font-style:normal">live embeds of <code class="kb">Ravilo Mobile.html</code></em> in its new window mode (no bezel, no status bar), so they cannot drift from the phone: tap anything. The desktop adds only the strip above; the bottom safe area shrinks to 6 px.');
  y += 130;
  frame(0, y, 'C·a', 'macOS · Films &amp; series · Home', 'The traffic lights get their own 32 px strip rather than sitting inside the phone’s top row. The phone’s screens stay untouched, and the strip is also where the window is dragged.', cwin('mac', 'aurora', 'mode=video&amp;tab=home&amp;skin=aurora', 'Ravilo'), 400);
  frame(460, y, 'C·b', 'GNOME · Profile: the switch', 'At this size the switch is the phone’s: Profile’s mode card. The close button sits alone on the right, as GNOME puts it.', cwin('gn', 'aurora', 'mode=video&amp;tab=profile&amp;skin=aurora', 'Ravilo'), 400);
  frame(920, y, 'C·c', 'macOS · Music · Listen', 'Music mode is the phone’s bar: Listen · Browse · Playing · Queue · Profile. The mini bar sits above the bar.', cwin('mac', 'aurora', 'mode=music&amp;skin=aurora', 'Ravilo'), 400);
  frame(1380, y, 'C·d', 'GNOME · Music · Midnight', 'Skins carry across, since the phone already has all three.', cwin('gn', 'midnight', 'mode=music&amp;skin=midnight', 'Ravilo'), 400);
  y += 1000;

  head(y, 'Medium · 600–839 dp · the sidebar folds into a rail (decided, Q8)', 'Between the phone and the sidebar, the sidebar keeps its order and its switch but loses its words. Everything stays one click away, and the switch stays visible, which is the point of D1. On the Mac the rail is still the glass panel with the traffic lights in it. On GNOME it is still the split view’s sidebar, with the primary menu above it.');
  y += 130;
  frame(0, y, 'M·a', 'macOS · Films &amp; series · Home · 720 px', 'Five pages under the toggle; Search is the first item because the field no longer fits. The hero keeps its full width.', mac({ w: 720, rail: 1, mode: 'films', active: 'Home', tb: macTb('', true), page: filmsHome() }), 720);
  frame(780, y, 'M·b', 'GNOME · Music · an album, queue open · 720 px', 'The queue opens <em>over</em> the content from the right (the split view’s end pane in overlay mode); Esc or a click on the album closes it. The bar drops shuffle, lyrics and the volume slider; the volume keys still work.', gn({ w: 720, rail: 1, mode: 'music', active: 'Albums', playing: 1, hb: gnHb('Salt on the Window', true), page: albumPage(true, true), bar: { q: 1, compact: 1 } }), 720);
  frame(1560, y, 'M·c', 'macOS · Music · Listen · 720 px', 'The capsule narrows the same way. The dot on <em>Playing</em> replaces the sidebar’s equaliser.', mac({ w: 720, rail: 1, mode: 'music', active: 'Listen', playing: 1, tb: macTb(''), page: listen(), bar: { compact: 1 } }), 720);
  frame(2340, y, 'M·alt', 'The alternative · the sidebar hides behind a button', 'This is how both platforms do it natively (AdwOverlaySplitView; the Mac’s sidebar toggle). But the switch disappears with the sidebar, and every page is two clicks away. Kept for the record; not chosen.', gn({ w: 720, noSide: 1, hb: `<div class="ghb center"><span class="gb bg">${ic('side')}</span><span class="tt">Home</span><span class="sp"></span><span class="gb">${ic('cast')}</span><span class="gx">${ic('x')}</span></div>`, over: `<div class="scrim"></div><div class="ovside">${gnSide({ mode: 'films', active: 'Home' })}</div>`, page: filmsHome() }), 720);
  y += 1000;

  head(y, 'Expanded and Large · the queue by width, and the bar in films mode', 'Q5: the side panel stays. Below 1200 dp it floats over the content so the album keeps its width; from 1200 it docks and pushes the content.');
  y += 130;
  frame(0, y, 'E·a', 'macOS · Expanded (1040 px) · queue over the album', 'The panel is its own glass sheet; the capsule shortens so it stays clear of it.', mac({ w: 1040, cls: 'qopen', mode: 'music', active: 'Albums', playing: 1, tb: macTb(''), page: albumPage(true, true), bar: { q: 1 } }), 1040);
  frame(1120, y, 'L·a', 'GNOME · Large (1200 px) · queue docked', 'Round 1’s D1·d, now defined as the Large size.', gn({ mode: 'music', active: 'Albums', playing: 1, hb: gnHb('Salt on the Window', true), page: albumPage(true), bar: { q: 1 } }), 1200);
  y += 1000;
  frame(0, y, 'E·b', 'macOS · Films &amp; series while music plays', 'Q2 + Q10: in films mode the capsule is there <em>only while music plays</em>. Pause it from the capsule and it stays until you leave the page, so Play is one click away; on the next page it is gone. Nothing playing = no capsule (round 1’s D1·a). Music mode always has its bar: the last-played song, paused (R322).', mac({ mode: 'films', active: 'Home', tb: macTb('', true), page: filmsHome(), bar: {} }), 1200);
  y += 1000;

  head(y, 'Five themes · and a light one and a dark one, picked once', 'Owner, 2026-09-30: round 2’s System palettes are now two real themes, <em style="color:#fff;font-style:normal">Graphite</em> (dark, neutral greys, one blue) and <em style="color:#fff;font-style:normal">Daylight</em> (Ravilo’s first light theme, its own violet-to-blue). The list is Aurora · Midnight · Noir · Graphite · Daylight on every device that has a theme setting. Then, as in IntelliJ’s <em style="color:#fff;font-style:normal">Sync with OS</em>: a switch to follow the system, one theme for light, one for dark. Ravilo changes the moment the system does, with no restart and nothing lost. Themes keep Ravilo’s fonts in the content; the chrome is the system font in every theme (Q9).');
  y += 175;
  frame(0, y, 'T·a', 'macOS · Daylight', 'The selected sidebar row fills with the theme’s accent, white text, as the Mac draws selection. The hero keeps a dark scrim; artwork needs it in every theme.', mac({ skin: 'daylight', cls: 'lt', mode: 'films', active: 'Home', tb: macTb('', true), page: filmsHome() }), 1200);
  frame(1320, y, 'T·b', 'macOS · Graphite', 'Neutral greys, one blue, no gradient: the quietest of the dark themes.', mac({ skin: 'graphite', mode: 'music', active: 'Listen', playing: 1, tb: macTb(''), page: listen(), bar: {} }), 1200);
  y += 1000;
  frame(0, y, 'T·c', 'GNOME · Daylight', 'On GNOME the selection stays neutral grey (libadwaita), whatever the theme; the accent is on play and on links.', gn({ skin: 'daylight', cls: 'lt', mode: 'music', active: 'Albums', playing: 1, hb: gnHb('Salt on the Window', true), page: albumPage(true), bar: { q: 1 } }), 1200);
  frame(1320, y, 'T·d', 'GNOME · Graphite', 'Graphite sits closest to Adwaita’s own dark, so it reads as native on GNOME without being the system’s palette.', gn({ skin: 'graphite', mode: 'films', active: 'Home', hb: gnHb('Home'), page: filmsHome() }), 1200);
  y += 1000;
  const TH = [['Aurora', '#0a0c13', 'linear-gradient(120deg,#7b6ef0,#3fb6f5)', 'd'], ['Midnight', '#04101a', 'linear-gradient(120deg,#19d6c6,#2a8cf0)', 'd'], ['Noir', '#080807', 'linear-gradient(120deg,#f5b542,#e0792f)', 'd'], ['Graphite', '#1c1c1f', '#4f8ef0', 'd'], ['Daylight', '#fbfbfd', 'linear-gradient(120deg,#6a5cf0,#1f8fdc)', 'l']];
  const sws = (kind, on, n5) => `<div class="sw${n5 ? ' n5' : ''}">${TH.filter(t => !kind || t[3] === kind).map(([n, b, a]) => `<div class="${n === on ? 'on' : ''}"><i style="background:${b};--sa:${a}"></i>${n}</div>`).join('')}</div>`;
  const setTb = `<div class="tb">${L}<span class="on">${ic('side')}General</span><span>${ic('play')}Playback</span><span>${ic('person')}Account</span></div>`;
  const macSet = (skin, dark) => `<div class="setw mac${skin === 'daylight' ? ' lt' : ''}" data-skin="${skin}">${setTb}<div class="bd"><h6>Theme</h6><div class="throw"><span class="ck">✓</span>Match System Settings ▸ Appearance</div><div class="slot"><b>Light${dark ? '' : '<span class="now">in use now</span>'}</b>${sws('l', 'Daylight')}</div><div class="slot"><b>Dark${dark ? '<span class="now">in use now</span>' : ''}</b>${sws('d', 'Aurora')}</div><p style="margin:14px 0 0;font-size:12px;color:var(--ink-dim)">Saved to your profile: every TV, phone and computer you sign in on uses these.</p></div></div>`;
  frame(0, y, 'T·e', 'macOS · Settings (⌘,) · General · the Mac is light', 'Follow the system is on: two rows, light themes above, dark themes below, and the row in use now says so. The pair belongs to the viewer, not the Mac (owner): change it here and the phone and the TV change too; each device only decides <em>which</em> of the two it shows. Today the light row holds only Daylight; it grows as themes are added.', macSet('daylight', 0), 600);
  frame(700, y, 'T·f', '…19:00, the Mac turns dark (Auto)', 'The same window a second later: Ravilo repaints in Aurora while you look at it, and <em>in use now</em> moves down a row. A film or a song does not stop.', macSet('aurora', 1), 600);
  frame(1400, y, 'T·g', 'macOS · Follow the system off', 'One row of all five, and the pick holds whatever the Mac does. Turning follow off keeps the theme in use at that moment.', `<div class="setw mac" data-skin="graphite">${setTb}<div class="bd"><h6>Theme</h6><div class="throw"><span class="ck" style="background:none;box-shadow:inset 0 0 0 1.5px var(--ink-dim)"></span>Match System Settings ▸ Appearance</div>${sws(null, 'Graphite', 1)}<p style="margin:14px 0 0;font-size:12px;color:var(--ink-dim)">Saved to your profile: every TV, phone and computer you sign in on uses these.</p></div></div>`, 600);
  y += 520;
  const combo = (n, c) => `<span class="combo"><i style="background:${c}"></i>${n} ▾</span>`;
  frame(0, y, 'T·h', 'GNOME · Preferences · Appearance', 'AdwPreferencesDialog: a switch row, then two combo rows, native to GNOME. Light and dark come from the portal’s <code class="kb">color-scheme</code>, so the Quick Settings Dark Style toggle flips Ravilo live. Off: one combo row, <em>Theme</em>, with all five.', `<div class="setw gn" data-skin="aurora"><div class="hb">Preferences<span class="gx">${ic('x')}</span></div><div class="bd" style="padding-top:8px"><h6>Appearance</h6><p style="margin:-4px 0 10px;font-size:12px;color:var(--ink-dim)">Saved to your profile, so every device you sign in on uses these</p><div class="grp"><div>Follow the system style<span class="gtog"></span></div><div><span>Light style<div class="sub">Used when the desktop is light</div></span>${combo('Daylight', '#fbfbfd')}</div><div><span>Dark style<div class="sub">In use now</div></span>${combo('Aurora', '#7b6ef0')}</div></div><h6 style="margin-top:18px">Playback</h6><div class="grp"><div>Play the next episode automatically<span class="gtog"></span></div></div></div></div>`, 600);
  const cwin2 = (q, tag) => `<div class="win cwin mac" data-skin="daylight" style="height:760px"><div class="cstrip">${L}<span class="tag">${tag}</span></div><iframe src="Ravilo Mobile.html?frame=window&amp;${q}" title="${tag}"></iframe></div>`;
  frame(700, y, 'T·i', 'The phone · Settings ▸ Theme (live)', 'Q11: the phone gets the same five and the same pair, and they are the same settings as on the Mac: one profile, every device. Here it is pinned to show all five chips; switch <em>Match the phone’s light and dark</em> on for the two rows. Android follows the system’s dark theme; the iPhone web app follows iOS Appearance through <code class="kb">prefers-color-scheme</code>.', cwin2('skin=daylight&amp;sheet=settings', 'Ravilo · phone layout'), 400);
  frame(1160, y, 'T·j', 'The phone · Daylight · Music', 'Every screen in <code class="kb">Ravilo Mobile.html</code> now draws in Daylight; the hero card and the film player stay dark over their artwork. On the phone mockup, PREVIEW ▸ <em>Phone goes light ⇄ dark</em> stands in for the system switch.', cwin2('skin=daylight&amp;mode=music', 'Ravilo · phone layout'), 400);
  y += 1000;
  const DEC = [['Q1', 'D1: the switch heads the sidebar. Under 600 dp the window is the phone.'], ['Q2', 'In films mode the bar is there only while music plays (+ Q10).'], ['Q3', 'Five themes, Aurora · Midnight · Noir · <em>Graphite</em> · <em>Daylight</em>, plus <em>follow the system</em> with one light and one dark pick.'], ['Q4', 'System font (read as Q9).'], ['Q5', 'Side panel when wide, the phone’s page when compact, an overlay panel in between.'], ['Q6', 'Platform shape: glass capsule on macOS, docked bar on GNOME.'], ['Q7', 'Closing the window keeps music playing (Dock / Background Apps).'], ['Q8', 'Medium folds the sidebar into a rail with labels (M·a–M·c).'], ['Q9', 'The system font in the chrome in every theme; Ravilo’s Sora + Space Grotesk in titles, tiles and the player. The phone layout keeps its own fonts.'], ['Q10', 'In films mode, paused music keeps its capsule until you leave the page.'], ['Q11', 'The phone gets the five themes and the light/dark pair in the same release (T·i, T·j).']];
  const DEF = [['New install', 'Follow the system <em>on</em>, light = Daylight, dark = Aurora.'], ['Existing viewer', 'Follow off, single = the theme on the first device they open after the update; the other devices adopt it. Nobody’s Ravilo turns white overnight.'], ['Where it is kept', '<em>On the viewer’s profile, across devices</em> (owner, 2026-09-30), like R161/R162’s app language: <em>follow</em>, the light pick, the dark pick and the single pick sync. Only the light/dark state is each device’s own, so the Mac can be in Daylight while the TV is in Aurora with the same settings. A change reaches other signed-in devices live.'], ['TV', '<em>Dark-only</em> (owner, 2026-09-30): a TV, the receiver and the web app in a desktop browser have no light/dark of their own, so they always show the viewer’s <em>dark</em> pick. Their Settings ▸ Theme is one row of the four dark themes (<em>This TV is always dark</em>); a pick there sets the dark pick everywhere.']];
  out.push(`<div class="frm" style="left:0;top:${y}px"><div class="card"><h4>Decided (2026-09-30)</h4><table class="tbl">${DEC.map(r => `<tr><td style="width:44px"><span class="kb">${r[0]}</span></td><td>${r[1]}</td></tr>`).join('')}</table><h4 style="margin-top:26px">Defaults I have set (tell me if not)</h4><table class="tbl">${DEF.map(r => `<tr><td style="width:150px">${r[0]}</td><td>${r[1]}</td></tr>`).join('')}</table></div></div>`);
  const STR = [['theme.graphite', 'Graphite', 'Grafit', 'Grafitt'], ['theme.daylight', 'Daylight', 'Dagslys', 'Dagsljós'], ['theme.follow', 'Match the phone’s light and dark', 'Følg telefonens lys og mørk', 'Fylg ljósa og myrka á telefonini'], ['theme.follow_desk', 'Match the system appearance', 'Følg systemets udseende', 'Fylg útsjónd kervisins'], ['theme.follow_sub', 'Switches the moment the phone does', 'Skifter i det øjeblik telefonen gør', 'Skiftir sama løtu sum telefonin'], ['theme.when_light', 'When the phone is light', 'Når telefonen er lys', 'Tá ið telefonin er ljós'], ['theme.when_dark', 'When the phone is dark', 'Når telefonen er mørk', 'Tá ið telefonin er myrk'], ['theme.light', 'Light', 'Lys', 'Ljóst'], ['theme.dark', 'Dark', 'Mørk', 'Myrkt'], ['theme.in_use', 'In use now', 'I brug nu', 'Í nýtslu nú'], ['theme.dark_only', 'This TV is always dark', 'Dette tv er altid mørkt', 'Hetta sjónvarpið er altíð myrkt'], ['theme.synced', 'Saved to your profile: every TV, phone and computer you sign in on uses these.', 'Gemt på din profil: alle tv’er, telefoner og computere, du logger ind på, bruger dem.', 'Goymt á tínum vanga: øll sjónvørp, telefonir og teldur, tú ritar inn á, nýta tey.'], ['desk.show_sidebar', 'Show sidebar', 'Vis sidepanel', 'Vís síðuteig'], ['desk.close_queue', 'Close queue', 'Luk kø', 'Lat bíðirøð aftur']];
  out.push(`<div class="frm" style="left:1320px;top:${y}px"><div class="card"><h4>New strings (da/fo drafts)</h4><table class="tbl"><tr><th>key</th><th>en</th><th>da</th><th>fo</th></tr>${STR.map(r => `<tr><td><code>${r[0]}</code></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</table><p class="note" style="color:#9aa0b6">The desktop says “the system” (theme.follow_desk), the phone says “the phone”. Round 1’s nine <code class="kb">desk.*</code> strings stand.</p></div></div>`);

  document.body.insertAdjacentHTML('beforeend', out.join(''));
})();
