/* Playback sessions — §B1 on the desktop, §B4a volume on every non-mobile client, §B8 desktop specifics. */
(function () {
  const K = window.PSK, { put, G, S, ses, tgt, win, capsule, gbar, vrow, lbl, cap, note, rule, bg, TG, castic } = K;
  let Y = K.Y;
  const WX = 1240;
  const shelf = '<h2>Listen</h2><div class="lead">Good evening, Eyð</div><h4>Recently played</h4><div class="shelf">' + [['Salt on the Window', 'Harbour Lights', 'salt'], ['Quiet Hours', 'Marta Vang', 'quiet'], ['Low Water', 'The Ferrymen', 'low'], ['Signal Lamp', 'Copperline', 'sig'], ['Lichen', 'Moss Garden', 'lic']]
    .map(a => '<div><div class="a" style="' + bg(a[2]) + '"></div><div class="t">' + a[0] + '</div><div class="s">' + a[1] + '</div></div>').join('') + '</div><h4>Albums for the evening</h4><div class="shelf">' + [['Kvøld', 'Kvøld', 'mes'], ['Glass Birds', 'Copperline', 'low'], ['Tide Tables', 'Harbour Lights', 'salt'], ['Ferry Songs', 'The Ferrymen', 'som'], ['Moss', 'Moss Garden', 'lic']]
    .map(a => '<div><div class="a" style="' + bg(a[2]) + '"></div><div class="t">' + a[0] + '</div><div class="s">' + a[1] + '</div></div>').join('') + '</div>';
  const filmsHome = '<h2>Home</h2><div class="lead">Continue watching</div><div class="wide5">' + [['Sommeren ’92', 'som'], ['Lundin og vinir', 'lun'], ['Mesterholdet', 'mes']].map(a => '<div class="a" style="' + bg(a[1]) + '"><span>' + a[0] + '</span></div>').join('')
    + '</div><h4>New in Films</h4><div class="wide5">' + [['Kelp Forest', 'low'], ['Quiet Coast', 'quiet'], ['Glass Winter', 'lic']].map(a => '<div class="a" style="' + bg(a[1]) + '"><span>' + a[0] + '</span></div>').join('') + '</div>';
  const vw = { viewer: 'mac' };
  const sesPop = (cls, st, extra) => '<div class="ps-pop' + (cls || '') + '" style="' + st + '"><div class="ps-sec">Playing everywhere<span class="r">4</span></div>' + ses(S.music, vw) + ses(S.book, vw) + ses(S.film, vw) + ses(S.kid, vw)
    + '<div class="ps-sec">Play on…</div>' + tgt('mac', 'This Mac', '', { here: true }) + tgt('tv', 'Stue TV', 'Ravilo is on screen') + tgt('speaker', 'Kontor', 'Ready') + '<div class="ps-col"><span>More places</span><span style="color:var(--ink-dim)">(4)</span><span class="ct">' + G.down + '</span></div>' + (extra || '') + '</div>';

  const P = window.PS_PART || 1;
  K.mute = P === 2;
  /* ================= B1 · desktop ================= */
  rule(Y - 40);
  lbl(0, Y, '§B1 · on the desktop', 'The same three directions in the window (mac Large · GNOME Large)', 'The desktop has room, so each direction also gets a page: in A the sidebar’s <i>Playing</i> page gains the switcher row (the capsule’s session); in B that row <i>is</i> the direction; in C the sidebar gains <i>Rooms</i>. The <b>popover from the toolbar glyph</b> is A’s heart on every desktop. Frames drawn at 1120 × 720.', 'w3');
  Y += 130;
  cap(0, Y, 'A · mac · the glyph’s popover · capsule “+2”', 1100);
  win(0, Y + 36, { w: 1120, mode: 'music', active: 'Listen', title: '', castLit: true, castN: 3, page: shelf, bar: capsule(S.music, { more: 2 }), pop: sesPop('', 'right:14px;top:50px') }, 'A desktop · popover');
  cap(WX - 60, Y, 'B · mac · the Playing page with the switcher row', 1100);
  const playPage = (s, o) => { o = o || {}; return (o.sw === false ? '' : '<div class="ps-switch">' + [[S.music, 1], [S.book], [S.film], [S.kid]].map(([x, on]) => '<b class="' + (on ? 'on' : '') + '"><i style="' + bg(x.art) + '"></i>' + (x.who ? 'Olivar · ' : '') + (x.tgt === 'This phone' ? 'Pixel 9' : x.tgt) + '</b>').join('') + '</div>')
    + '<div class="ps-play"><div><div class="cv" style="' + bg(s.art) + '"></div></div><div><div style="font-size:12px;font-weight:700;letter-spacing:.07em;text-transform:uppercase;color:var(--accent-2);display:flex;align-items:center;gap:7px">' + TG[s.tk].replace('<svg', '<svg style="width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:2"') + 'Playing on ' + s.tgt + '</div><h3 style="margin-top:8px">' + s.title + '</h3><div class="ar">' + s.sub + ' · Salt on the Window</div>' + (o.right || '') + '</div></div>'; };
  const upNext = '<div class="ps-card"><div class="hd">Up next<span class="r">Edit</span></div>' + ['Eleven Days · 5:02', 'Winter Tour · 4:27', 'Åsen · 3:31'].map(t => '<div style="display:flex;padding:9px 16px;border-top:1px solid var(--line);font-size:13px"><span>' + t.split(' · ')[0] + '</span><span style="margin-left:auto;color:var(--ink-dim)">' + t.split(' · ')[1] + '</span></div>').join('') + '</div>';
  win(WX - 60, Y + 36, { w: 1120, mode: 'music', active: 'Playing', extraNav: { Playing: '<span class="n hot">4</span>' }, title: '', castLit: true, page: playPage(S.music, { right: upNext }), bar: capsule(S.music) }, 'B desktop · Playing page');
  cap(WX * 2 - 120, Y, 'C · GNOME · a Rooms page', 1100);
  const rc = (kind, name, s, o) => { o = o || {}; return '<div style="border-radius:12px;background:rgba(255,255,255,.045);border:1px solid ' + (o.mine ? 'rgba(63,182,245,.45)' : 'var(--line)') + ';padding:14px 16px"><div style="display:flex;align-items:center;gap:8px;font-size:12.5px;font-weight:700;color:var(--ink-soft)">' + TG[kind].replace('<svg', '<svg style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2"') + name + '<span style="margin-left:auto;font-weight:500">' + (o.r || '') + '</span></div>'
    + (s ? '<div style="display:flex;gap:12px;align-items:center;margin-top:12px"><span style="width:' + (s.kind === 'music' || s.kind === 'book' ? 54 : 86) + 'px;height:54px;border-radius:8px;flex:none;' + bg(s.art) + '"></span><div style="min-width:0;flex:1"><div style="font-weight:700;font-size:14px">' + (s.kind === 'ep' ? s.title + ' · ' + s.sub : s.title) + '</div><div style="font-size:12.5px;color:var(--ink-soft);margin-top:3px">' + (o.s || '') + '</div></div></div>'
      : '<div style="margin-top:12px;font-size:13px;color:var(--ink-soft);display:flex;justify-content:space-between"><span>Nothing playing</span><b style="color:var(--accent-2)">Play something here</b></div>') + '</div>'; };
  const rooms = '<h2>Rooms</h2><div class="lead">Everywhere Ravilo can play in this house</div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:12px">'
    + rc('mac', 'This computer', null) + rc('group', 'Stue + Gæsteværelse', S.music, { mine: true, s: 'Harbour Lights · playing' }) + rc('phone', 'Pixel 9', S.book, { s: 'Kapitel 3 · playing' }) + rc('tv', 'Soveværelse TV', S.film, { s: 'Paused at 48:10' })
    + rc('hub', 'Køkken hub', S.kid, { r: 'Olivar', s: 'Olivar is watching' }) + rc('tv', 'Stue TV', null) + '</div>';
  win(WX * 2 - 120, Y + 36, { w: 1120, gn: true, mode: 'films', active: '', navAdd: '<h6>House</h6><a class="on">' + G.rooms + '<span>Rooms</span><span class="n hot">4</span></a>', title: 'Rooms', page: rooms, bar: gbar(S.music, { more: 2 }) }, 'C desktop · Rooms');

  /* ================= B4a · volume on non-mobile clients ================= */
  Y += 900;
  if (P === 1) { K.Y = Y; K.mute = false; K.flush(); return; }
  K.mute = false; Y = K.Y + 40;
  rule(Y - 40);
  lbl(0, Y, { t: '§B4a · required on every non-mobile client (owner, 2026-10-02)' }, 'Volume of a session on several speakers', 'A phone has its keys and its own output panel. The <b>Mac, Linux, the web app and the TV have nothing</b>, so Ravilo carries it: the bar’s volume button is the <b>master</b> (all rooms together, keeping their balance); a disclosure <b>Speakers ▾</b> opens each room’s own slider + mute, in the order they joined, with <i>Add a speaker…</i> in the same place. Every level is the room’s <b>real</b> one on arrival; a change from a phone key, the speakers’ app or the server’s dashboard moves the sliders live. TV version: §B9.', 'w3');
  Y += 150;
  const volPop = (cls, st, o) => { o = o || {}; return '<div class="ps-pop' + (cls || '') + '" style="' + st + '"><div class="ph">' + G.group.replace('<svg', '<svg style="width:17px;height:17px;fill:none;stroke:var(--accent-2);stroke-width:2"') + 'Stue + Gæsteværelse<span class="r">Cannery Lights</span></div>'
    + vrow('vol', 'Volume', 32, { master: true }) + '<div class="ps-disc">' + G.down + 'Speakers<span class="r">' + (o.n || 3) + '</span></div>'
    + vrow('speaker', 'Stue', 40) + vrow('speaker', 'Gæsteværelse', 24, { muted: o.muted }) + (o.gone ? vrow('speaker', 'Kontor', 0, { gone: 'Left the group at 20.39 · <span class="lnk">Add back</span>' }) : '')
    + '<div class="ps-add">' + G.plus + '<span>Add a speaker…</span></div>' + (o.foot ? '<div class="ps-foot">' + o.foot + '</div>' : '') + '</div>'; };
  cap(0, Y, '4a·1 · mac · the capsule’s volume popover · expanded', 1100);
  win(0, Y + 36, { w: 1120, mode: 'music', active: 'Listen', castLit: true, castN: 3, page: shelf, bar: capsule(S.music, { more: 2, volOn: true }), pop: volPop('', 'right:150px;bottom:86px', { muted: true, gone: true, n: 3, foot: 'Køkken hub is busy — Olivar is watching. It can join when he is done.' }) }, '4a·1 mac volume');
  note(0, Y + 770, '<b>Master</b> 32 % is the session’s; Stue 40 % and Gæsteværelse 24 % are the rooms’ own. Dragging master to 64 % takes them to 80 % and 48 %. <b>Muted</b> keeps the level for un-mute. <b>Kontor left</b> (unplugged, or someone took it in the speakers’ app): listed with <i>Add back</i> until the session ends. Space and the media keys act on the capsule’s session; ⌥↑/⌥↓ move master.', 1100);
  cap(WX - 60, Y, '4a·2 · GNOME · the docked bar’s volume menu button', 1100);
  win(WX - 60, Y + 36, { w: 1120, gn: true, mode: 'music', active: 'Listen', title: 'Listen', castLit: true, page: shelf, bar: gbar(S.music, { volOn: true, more: 2 }) }, '4a·2 GNOME volume');
  put('<div style="position:absolute;left:' + (WX - 60 + 1120 - 520) + 'px;top:' + (Y + 36 + 720 - 72 - 372) + 'px;z-index:5" data-skin="aurora">' + volPop(' gn', 'position:relative') + '</div>');
  note(WX - 60, Y + 770, 'Same list as an Adwaita popover above the bar’s <b>32 % ▾</b> button (a menu button, not a slider in the bar — GNOME’s own volume idiom). Arrow keys move between rows, ←/→ change the focused one, M mutes. <span class="ps-tag dep">depends on §8 Q5a</span> a room’s own level inside a group from our desktop sender is untested; master is safe today.', 1100);
  cap(WX * 2 - 120, Y, '4a·3 · states of the same popover', 1100);
  const mini1 = '<div class="ps-pop" style="position:relative;width:auto"><div class="ph">' + G.speaker.replace('<svg', '<svg style="width:17px;height:17px;fill:none;stroke:var(--accent-2);stroke-width:2"') + 'Stue<span class="r">one speaker</span></div>' + vrow('speaker', 'Volume', 40, { master: true }) + '<div class="ps-add">' + G.plus + '<span>Add a speaker…</span></div></div>';
  const unk = '<div class="ps-pop" style="position:relative;width:auto"><div class="ph">' + G.group.replace('<svg', '<svg style="width:17px;height:17px;fill:none;stroke:var(--accent-2);stroke-width:2"') + 'Stue + Gæsteværelse<span class="r">reconnecting</span></div>' + vrow('vol', 'Volume', 32, { master: true }) + '<div class="ps-disc">' + G.down + 'Speakers</div>' + vrow('speaker', 'Stue', 40) + '<div class="ps-vrow gone"><span class="ic">' + G.speaker + '</span><span class="nm">Gæsteværelse<span class="v">—</span></span><span class="mu"></span><span class="sub">Offline · level unknown</span></div></div>';
  const other = '<div class="ps-pop" style="position:relative;width:auto"><div class="ph">' + G.hub.replace('<svg', '<svg style="width:17px;height:17px;fill:none;stroke:var(--ink-soft);stroke-width:2"') + 'Køkken hub<span class="r">Olivar</span></div><div class="ps-vrow"><span class="ic">' + G.hub + '</span><span class="nm">Olivar is watching<span class="v">45%</span></span><span class="mu"></span><span class="tr" style="opacity:.0"></span><span class="sub">Only Olivar can change it (Q1).</span></div></div>';
  put('<div style="position:absolute;left:' + (WX * 2 - 120) + 'px;top:' + (Y + 36) + 'px;width:1120px;display:grid;grid-template-columns:repeat(3,1fr);gap:18px;align-items:start" data-skin="aurora">'
    + [['one speaker', 'just the master', mini1, 'No disclosure: one slider. <i>Add a speaker…</i> makes it a group.'], ['offline room', 'never a default', unk, 'An unknown level shows <b>—</b>, never 50 %. The slider returns with the real value.'], ['another person', 'Q1 lean', other, 'Shown so you know why the room is busy; no slider.']]
      .map(c => '<div class="st-cell"><div class="h"><b>' + c[0] + '</b><span>' + c[1] + '</span></div><div style="padding:12px">' + c[2] + '</div><div class="cp">' + c[3] + '</div></div>').join('') + '</div>');
  Y += 880;
  cap(0, Y, '4a·4 · mac · the Playing page · Speakers card in the right column', 1100);
  const spkCard = '<div class="ps-card"><div class="hd">Speakers<span class="r">Add a speaker…</span></div>' + vrow('vol', 'Volume', 32, { master: true }) + vrow('speaker', 'Stue', 40) + vrow('speaker', 'Gæsteværelse', 24) + '</div>';
  win(0, Y + 36, { w: 1120, mode: 'music', active: 'Playing', title: '', castLit: true, castN: 3, page: playPage(S.music, { sw: false, right: '<div class="ps-seek" style="margin-top:18px"><div class="tr"><i style="width:31%"></i><u style="left:31%"></u></div><div class="tm"><span>1:12</span><span>3:55</span></div></div>' + spkCard + upNext.replace('margin-top:16px', '') }), bar: capsule(S.music, { more: 2 }) }, '4a·4 Playing page');
  note(0, Y + 770, 'On the Playing page the list is always open (there is room). The page header is the place line — <i>Playing on Stue + Gæsteværelse</i> — and opens <i>Move to…</i>.', 1100);
  cap(WX - 60, Y, '4a·5 · the web app’s player · same popover from the mouse', 1100);
  put('<div class="ps-br" data-skin="aurora" style="left:' + (WX - 60) + 'px;top:' + (Y + 36) + 'px;width:1120px;height:720px" data-screen-label="4a·5 web"><div class="bar"><i></i><i></i><i></i><span class="url">ravilo.home/web · Ravilo</span></div><div class="vp" style="background:var(--bg)">'
    + '<div style="position:absolute;inset:0;' + bg('salt') + ';opacity:.35"></div><div style="position:absolute;left:60px;top:60px;width:320px;height:320px;border-radius:18px;' + bg('salt') + ';box-shadow:0 30px 70px rgba(0,0,0,.5)"></div>'
    + '<div style="position:absolute;left:420px;top:90px"><div style="font-size:14px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--accent-2)">Playing on Stue + Gæsteværelse</div><div style="font-family:\'Space Grotesk\',sans-serif;font-size:44px;font-weight:700;margin-top:12px">Cannery Lights</div><div style="font-size:18px;color:var(--ink-soft);margin-top:6px">Harbour Lights</div></div>'
    + '<div style="position:absolute;left:60px;right:60px;bottom:40px;display:flex;align-items:center;gap:18px"><span style="width:56px;height:56px;border-radius:50%;background:var(--ink);display:flex;align-items:center;justify-content:center">' + G.pause.replace('<svg', '<svg style="width:24px;height:24px;fill:var(--bg)"') + '</span><span style="flex:1;height:5px;border-radius:3px;background:rgba(255,255,255,.18);position:relative"><i style="position:absolute;left:0;top:0;bottom:0;width:31%;border-radius:3px;background:var(--ink)"></i></span><span style="font-family:\'JetBrains Mono\',monospace;font-size:14px;color:var(--ink-soft)">1:12 / 3:55</span><span style="height:44px;padding:0 16px;border-radius:22px;background:rgba(255,255,255,.14);display:flex;align-items:center;gap:8px;font-size:15px;font-weight:600">' + G.vol.replace('<svg', '<svg style="width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:2"') + '32 %</span></div>'
    + volPop('', 'right:60px;bottom:100px') + '</div></div>');
  note(WX - 60, Y + 770, 'The web app is a <b>controller only</b> for speakers (no browser can start a cast; report §8 Q8). It reaches the rooms through the server, so the same popover works — mouse, or Tab/arrow keys with a visible focus ring.', 1100);
  put('<div class="ps-note" style="left:' + (WX * 2 - 120) + 'px;top:' + (Y + 36) + 'px;width:1120px;font-size:.84rem"><b>How the numbers stay the same everywhere.</b> The session holds one volume per room (report §4.1 <span style="font-family:JetBrains Mono,monospace">options</span>). Every client renders it; a change from any of them — or from a phone’s keys, the speakers’ own app, the server’s dashboard — is a command against the session, and every slider moves within one report. A client never keeps its own copy: a slider that has not heard from the server shows <b>—</b>, not a guess.<br><br><b>Order of the rooms:</b> the order they joined (owner’s brief). Master is the session’s overall level; the rooms keep their ratios when it moves, and a room at 0 stays at 0.<br><br><b>What the phone adds:</b> nothing new — B4·b’s Speakers sheet is this list in a sheet, and the keys drive master.</div>');

  /* ================= B8 · desktop specifics ================= */
  Y += 900;
  rule(Y - 40);
  lbl(0, Y, '§B8 · desktop specifics', 'The capsule lights up as a remote', 'A session started on the phone appears on the Mac within a second: the capsule (mac) / docked bar (GNOME) shows it with the place chip, and Space and the media keys control it. In <b>films mode</b> the bar appears for it because music plays (R337 Q2). The toolbar glyph carries the count; its popover is §B1-A and the <i>Play on…</i> list (§B3) on a computer.', 'w3');
  Y += 130;
  cap(0, Y, 'B8·a · mac · films mode · the phone just cast to Stue + Gæsteværelse', 1100);
  win(0, Y + 36, { w: 1120, mode: 'films', active: 'Home', castLit: true, castN: 3, page: filmsHome, bar: capsule(S.music, { more: 2 }) }, 'B8a mac films remote');
  note(0, Y + 770, 'Nothing else changes in the window. The chip <b>Stue + Gæsteværelse</b> opens <i>Move to…</i>; the capsule’s art opens the Playing page as the remote. Closing the window leaves the session playing (it never lived here).', 1100);
  cap(WX - 60, Y, 'B8·b · GNOME · Play on… from the header bar · video mode', 1100);
  win(WX - 60, Y + 36, { w: 1120, gn: true, mode: 'films', active: 'Home', title: 'Home', castLit: false, page: filmsHome, bar: gbar(S.music, { more: 2 }), pop: '<div class="ps-pop gn" style="right:56px;top:50px"><div class="ps-sec">Play “Sommeren ’92” on…</div>' + tgt('mac', 'This computer', '', { here: true }) + '<div class="ps-sec">Your Ravilo apps</div>' + tgt('tv', 'Stue TV', 'Ravilo is on screen') + '<div class="ps-sec">Displays</div>' + tgt('hub', 'Køkken hub', 'Busy · Olivar is watching', { rt: false }) + '<div class="ps-col"><span>All your TVs</span><span style="color:var(--ink-dim)">(2)</span><span class="ct">' + G.down + '</span></div></div>' }, 'B8b GNOME play on');
  note(WX - 60, Y + 770, 'From a title page, the glyph opens <i>Play “Sommeren ’92” on…</i>. The Linux and Mac apps reach displays with our own sender (R330). Speakers are absent for a film, as on the phone.', 1100);
  put('<div class="panel" style="left:' + (WX * 2 - 120) + 'px;top:' + (Y + 36) + 'px;width:1044px"><h2>Keys on a computer</h2><table class="tbl"><tr><th style="width:220px">Key</th><th>Acts on</th></tr>'
    + '<tr><td><b>Space · ⏯ media key</b></td><td>The capsule’s session, wherever it plays.</td></tr>'
    + '<tr><td><b>⏭ ⏮ · ⌘→ ⌘←</b></td><td>Next / previous in that session (song, chapter, episode).</td></tr>'
    + '<tr><td><b>⌥↑ ⌥↓ (mac) · Ctrl↑ Ctrl↓ (GNOME)</b></td><td>Master volume of that session. The system volume keys stay the computer’s own.</td></tr>'
    + '<tr><td><b>⌘⇧P · Ctrl⇧P</b></td><td>Opens the glyph’s popover (<i>Playing everywhere</i> + <i>Play on…</i>). ↑↓ move, Return opens a remote, ⌫ stops the focused one after a second press.</td></tr>'
    + '<tr><td><b>View ▸ Playing everywhere</b></td><td>mac menu bar / GNOME ☰ — the same popover, so it is findable without the glyph.</td></tr></table>'
    + '<div class="warn"><b>Which session is the capsule’s</b> follows B2·b (owner 10-04): always the one this computer touched last; before it touches any, the newest playing. Switching: the +2 chip, or a row in the popover (it becomes the capsule’s).</div></div>');
  K.Y = Y + 900;
  K.flush();
})();
